'use strict'
// auto generated by vue-cli
// Template version: 1.2.6
// see http://vuejs-templates.github.io/webpack for documentation.

const path = require('path')

module.exports = {
  dev: {

    // Paths
    assetsSubDirectory: 'src/styles',
    assetsPublicPath: '/',
    //相当于V+2.0的web.config.js 用于开发环境
    proxyTable: {
      '/eap-auth': {
        target: 'http://10.66.196.45:8080',//测试 http://172.30.1.190  研发 http://10.23.22.31 OR 其他某个后端研发的IP：PORT
        pathRewrite: {
          '^/eap-auth': '/eap-auth'
        }
      },
      '/basic': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/basic': '/basic'
        }
      },
      '/dota': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/dota': '/dota'
        }
      },
      '/ecomodel': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/ecomodel': '/ecomodel'
        }
      },
      '/leadsafe': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/leadsafe': '/leadsafe'
        }
      },
      '/platform': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/platform': '/platform'
        }
      },
      '/preodo': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/preodo': '/preodo'
        }
      },
      '/tranbest': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/tranbest': '/tranbest'
        }
      },
      '/tyrewatch': {
        target: '/',//测试 http://172.30.1.190  研发 http://10.23.22.31
        pathRewrite: {
          '^/tyrewatch': '/tyrewatch'
        }
      }
    },
    // Various Dev Server settings
    host: 'localhost', // can be overwritten by process.env.HOST 一般是自己的IP地址 如果不需要给其他人访问可以直接写localhost 或 127.0.0.1
    port: 8088, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
    autoOpenBrowser: true,
    errorOverlay: true,
    notifyOnErrors: false,
    poll: false, // https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-

    // Use Eslint Loader?
    // If true, your code will be linted during bundling and
    // linting errors and warnings will be shown in the console.
    useEslint: false,
    // If true, eslint errors and warnings will also be shown in the error overlay
    // in the browser.
    showEslintErrorsInOverlay: false,

    /**
     * Source Maps
     */
    // source map 用于解决生产环境打包后线上定位BUG的问题，设置后需要同时开启chrome devtool设置中的 source map 选项
    // https://webpack.js.org/configuration/devtool/#development
    devtool: '#cheap-source-map',

    // If you have problems debugging vue-files in devtools,
    // set this to false - it *may* help
    // https://vue-loader.vuejs.org/en/options.html#cachebusting
    cacheBusting: true,

    // CSS Sourcemaps off by default because relative paths are "buggy"
    // with this option, according to the CSS-Loader README
    // (https://github.com/webpack/css-loader#sourcemaps)
    // In our experience, they generally work as expected,
    // just be aware of this issue when enabling this option.
    cssSourceMap: false,
  },
  // 打包生产环境设置
  build: {
    // Template for index.html
    index: path.resolve(__dirname, '../dist/index.html'),

    // Paths
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',

    // you can set by youself according to actual condition
    assetsPublicPath: './',

    /**
     * Source Maps
     */

    productionSourceMap: false,
    // https://webpack.js.org/configuration/devtool/#production
    devtool: '#source-map',

    // Gzip off by default as many popular static hosts such as
    // Surge or Netlify already gzip all static assets for you.
    // Before setting to `true`, make sure to:
    // npm install --save-dev compression-webpack-plugin
    productionGzip: false,
    productionGzipExtensions: ['js', 'css'],

    // Run the build command with an extra argument to
    // View the bundle analyzer report after build finishes:
    // `npm run build --report`
    // Set to `true` or `false` to always turn it on or off
    bundleAnalyzerReport: process.env.npm_config_report,
    useEslint: false
  }
}
